# Book settings
title: My sample book
author: The Jupyter Book Community
exclude_patterns: [README.md]

latex:
  latex_documents:
    targetname: book.tex

sphinx:
  extra_extensions:
    - sphinx_exercise
    - sphinx_togglebutton
